// deno-lint-ignore-file ban-types
import { extend } from "./extend.ts";
import { executable, route } from "./route.ts";
import type { Definition, Done, Route } from "./types.ts";

export type CommandZero<N extends string = string> = Route<
  N,
  "help" | "execute",
  {},
  [],
  [Done<{}, []>]
>;

export function command<const N extends string>(
  start: Definition<N>,
): CommandZero<N>;

export function command<const N extends string, A>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
): A;

export function command<const N extends string, A, B>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
): B;

export function command<const N extends string, A, B, C>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
): C;

export function command<const N extends string, A, B, C, D>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
): D;

export function command<const N extends string, A, B, C, D, E>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
): E;

export function command<const N extends string, A, B, C, D, E, F>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
): F;

export function command<
  const N extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
): G;

export function command<
  const N extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
): H;

export function command<
  const N extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
>(
  start: Definition<N>,
  na: (value: CommandZero<N>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
): I;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
): J;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
): K;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
): L;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
): M;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
): N;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
): O;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
): P;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
): Q;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
): R;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
): S;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
): T;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
): U;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
): V;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
): W;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
): X;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
): Y;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
): Z;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
): AA;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
): AB;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
): AC;

export function command<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
>(
  start: Definition<Name>,
  na: (value: CommandZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
): AD;

export function command(
  start: Definition<string>,
  ...elements: readonly ((value: never) => unknown)[]
): unknown {
  return extend(elements)(route(start, executable()));
}
