export function extend(): <T>(value: T) => T;

export function extend<A, B>(
  ab: (value: A) => B,
): (value: A) => B;

export function extend<A, B, C>(
  ab: (value: A) => B,
  bc: (value: B) => C,
): (value: A) => C;

export function extend<A, B, C, D>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
): (value: A) => D;

export function extend<A, B, C, D, E>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
): (value: A) => E;

export function extend<A, B, C, D, E, F>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
): (value: A) => F;

export function extend<A, B, C, D, E, F, G>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
): (value: A) => G;

export function extend<A, B, C, D, E, F, G, H>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
): (value: A) => H;

export function extend<A, B, C, D, E, F, G, H, I>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
): (value: A) => I;

export function extend<A, B, C, D, E, F, G, H, I, J>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
): (value: A) => J;

export function extend<A, B, C, D, E, F, G, H, I, J, K>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
): (value: A) => K;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
): (value: A) => L;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
): (value: A) => M;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
): (value: A) => N;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
): (value: A) => O;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
): (value: A) => P;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
): (value: A) => Q;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
): (value: A) => R;

export function extend<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
): (value: A) => S;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
): (value: A) => T;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
): (value: A) => U;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
): (value: A) => V;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
): (value: A) => W;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
): (value: A) => X;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
): (value: A) => Y;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
): (value: A) => Z;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
): (value: A) => AA;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
): (value: A) => AB;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
): (value: A) => AC;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
): (value: A) => AD;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
): (value: A) => AE;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
): (value: A) => AF;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
): (value: A) => AG;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
): (value: A) => AH;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
): (value: A) => AI;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
): (value: A) => AJ;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
): (value: A) => AK;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
): (value: A) => AL;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
): (value: A) => AM;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
): (value: A) => AN;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
): (value: A) => AO;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
): (value: A) => AP;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
): (value: A) => AQ;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
): (value: A) => AR;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
): (value: A) => AS;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
): (value: A) => AT;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
  AU,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
  atau: (value: AT) => AU,
): (value: A) => AU;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
  AU,
  AV,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
  atau: (value: AT) => AU,
  auav: (value: AU) => AV,
): (value: A) => AV;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
  AU,
  AV,
  AW,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
  atau: (value: AT) => AU,
  auav: (value: AU) => AV,
  avaw: (value: AV) => AW,
): (value: A) => AW;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
  AU,
  AV,
  AW,
  AX,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
  atau: (value: AT) => AU,
  auav: (value: AU) => AV,
  avaw: (value: AV) => AW,
  awax: (value: AW) => AX,
): (value: A) => AX;

export function extend<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
  AG,
  AH,
  AI,
  AJ,
  AK,
  AL,
  AM,
  AN,
  AO,
  AP,
  AQ,
  AR,
  AS,
  AT,
  AU,
  AV,
  AW,
  AX,
  AY,
>(
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
  adae: (value: AD) => AE,
  aeaf: (value: AE) => AF,
  afag: (value: AF) => AG,
  agah: (value: AG) => AH,
  ahai: (value: AH) => AI,
  aiaj: (value: AI) => AJ,
  ajak: (value: AJ) => AK,
  akal: (value: AK) => AL,
  alam: (value: AL) => AM,
  aman: (value: AM) => AN,
  anao: (value: AN) => AO,
  aoap: (value: AO) => AP,
  apaq: (value: AP) => AQ,
  aqar: (value: AQ) => AR,
  aras: (value: AR) => AS,
  asat: (value: AS) => AT,
  atau: (value: AT) => AU,
  auav: (value: AU) => AV,
  avaw: (value: AV) => AW,
  awax: (value: AW) => AX,
  axay: (value: AX) => AY,
): (value: A) => AY;

export function extend(
  elements: readonly ((value: never) => unknown)[],
): (value: unknown) => unknown;

export function extend(
  ...input:
    | readonly ((value: never) => unknown)[]
    | readonly [readonly ((value: never) => unknown)[]]
): unknown {
  let elements = input.length === 1 && Array.isArray(input[0])
    ? input[0] as readonly ((value: never) => unknown)[]
    : input as readonly ((value: never) => unknown)[];
  return (start: unknown): unknown =>
    elements.reduce<unknown>(
      (value, element) => element(value as never),
      start,
    );
}
