// deno-lint-ignore-file ban-types
import type {
  AnyRoute,
  Definition,
  Method,
  MethodsOf,
  ModelOf,
  Route,
} from "./types.ts";

export type RouteZero<N extends string = string> = Route<N, "help", {}, []>;

export function route<const Name extends string>(
  start: Definition<Name>,
): RouteZero<Name>;

export function route<const Name extends string, A>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
): A;

export function route<const Name extends string, A, B>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
): B;

export function route<const Name extends string, A, B, C>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
): C;

export function route<const Name extends string, A, B, C, D>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
): D;

export function route<const Name extends string, A, B, C, D, E>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
): E;

export function route<const Name extends string, A, B, C, D, E, F>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
): F;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
): G;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
): H;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
): I;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
): J;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
): K;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
): L;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
): M;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
): N;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
): O;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
): P;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
): Q;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
): R;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
): S;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
): T;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
): U;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
): V;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
): W;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
): X;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
): Y;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
): Z;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
): AA;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
): AB;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
): AC;

export function route<
  const Name extends string,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
>(
  start: Definition<Name>,
  na: (value: RouteZero<Name>) => A,
  ab: (value: A) => B,
  bc: (value: B) => C,
  cd: (value: C) => D,
  de: (value: D) => E,
  ef: (value: E) => F,
  fg: (value: F) => G,
  gh: (value: G) => H,
  hi: (value: H) => I,
  ij: (value: I) => J,
  jk: (value: J) => K,
  kl: (value: K) => L,
  lm: (value: L) => M,
  mn: (value: M) => N,
  no: (value: N) => O,
  op: (value: O) => P,
  pq: (value: P) => Q,
  qr: (value: Q) => R,
  rs: (value: R) => S,
  st: (value: S) => T,
  tu: (value: T) => U,
  uv: (value: U) => V,
  vw: (value: V) => W,
  wx: (value: W) => X,
  xy: (value: X) => Y,
  yz: (value: Y) => Z,
  zaa: (value: Z) => AA,
  aaab: (value: AA) => AB,
  abac: (value: AB) => AC,
  acad: (value: AC) => AD,
): AD;

export function route(
  start: Definition<string>,
  ...elements: readonly ((value: never) => unknown)[]
): unknown {
  let zero: RouteZero = {
    ...start,
    methods: ["help"],
    params: {},
    children: [],
  };

  return elements.reduce<unknown>(
    (value, element) => element(value as never),
    zero,
  );
}

export function version(
  semver: string,
): <
  const N extends string,
  const M extends Method,
  const T extends object,
  const C extends readonly AnyRoute[],
>(route: Route<N, M, T, C>) => Route<N, M | "version", T, C> {
  return (route) => ({
    ...route,
    methods: [...route.methods, "version"] as const,
    version: semver,
  });
}

export function executable(): <
  const N extends string,
  const M extends Method,
  const T extends object,
  const C extends readonly AnyRoute[],
>(route: Route<N, M, T, C>) => Route<N, M | "execute", T, C> {
  return (route) => ({
    ...route,
    methods: [...route.methods, "execute"] as const,
  });
}

export function routes<const C extends readonly AnyRoute[]>(
  ...children: C
): <R extends AnyRoute>(
  route: R,
) => Route<
  R["name"],
  MethodsOf<R>,
  ModelOf<R>,
  readonly [...R["children"], ...C]
> {
  return <R extends AnyRoute>(route: R) => {
    type Output = Route<
      R["name"],
      MethodsOf<R>,
      ModelOf<R>,
      readonly [...R["children"], ...C]
    >;

    return {
      ...route,
      children: [
        ...route.children,
        ...children,
      ] as unknown as Output["children"],
      params: route.params as Output["params"],
    };
  };
}
